name: CI workflow
on:
    push:
        branches: 
            - main
    pull_request: 
        branches:
            - main
jobs:
  build:
    runs-on: ubuntu-latest
    container: python:3.9-slim
    steps:
        - name: Checkout
          uses: actions/checkout@v3

          # This will cache dependencies for later workflow runs
        - name: Cache dependencies
          uses: actions/cache@v2
          with:
            path: ~/.cache/pip
            key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
            restore-keys: |
              ${{ runner.os }}-pip-
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
            pip install pylint

        - name: Lint with flake8
          run: flake8 src --count --select=E9,F63,F7,F82 --show-source --statistics
        - name: Lint with flake8 (Complexity)
          run: flake8 src --count --max-complexity=10 --max-line-length=127 --statistics
        - name: Run unit tests with nose
          run: nosetests -v --with-spec --spec-color --with-coverage --cover-package=app

        # Static Code Analysis with PyLint
        - name: Static Code Analysis with PyLint
          run: pylint src  







