name: CI workflow

on:
    push: "main"
    branches: []
    pull_request: pull


jobs:
  build:
    steps:
      Checkout:
      uses: actions/checout@v3

      Install dependencies:
      run: python -m pip install --upgrade pip | pip install -r requirements.txt

      Lint with flake8:
        run: flake8 src --count --select=E9,F63,F7,F82 --show-source --statistics | flake8 src --count --max-complexity=10 --max-line-length=127 --statistics

      Run unit tests with nose:
        run: nosetests -v --with-spec --spec-color --with-coverage --cover-package=app

    runs-on: ubuntu-latest
    container: python:3.9-slim





